name: zanpakuto_ichigo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^6.1.1
  flutter:
    sdk: flutter
  get: 4.6.5
  getwidget: ^3.0.1
  google_fonts: ^3.0.1
  http: ^0.13.5
  firebase_core: ^2.4.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
